### ISSUE TITLE
Add Swagger/OpenAPI docs

### ISSUE THREAD

**Issue by pjalsGit** [modrinth/docs#26]
I'm not sure if to put this on labrinth's repo or this repo, I'll just put it here.

It would be nice if there would be an [OpenAPI](https://en.wikipedia.org/wiki/OpenAPI_Specification) (formerly [Swagger](https://en.wikipedia.org/wiki/Swagger_(software))) endpoint.

Definitely not copied from Wikipedia:

The OpenAPI Specification, previously known as the Swagger Specification, is a [specification](https://en.wikipedia.org/wiki/Specification_(technical_standard)) for [machine-readable](https://en.wikipedia.org/wiki/Machine-readable_medium) [interface](https://en.wikipedia.org/wiki/Interface_(computing)) files for describing, producing, consuming, and visualizing [RESTful](https://en.wikipedia.org/wiki/Representational_state_transfer) [web services](https://en.wikipedia.org/wiki/Web_API). Previously part of the [Swagger](https://en.wikipedia.org/wiki/Swagger_(software)) framework, it became a separate project in 2016, overseen by the OpenAPI Initiative, an open-source collaboration project of the [Linux Foundation](https://en.wikipedia.org/wiki/Linux_Foundation).  Swagger and some other tools can generate code, documentation, and test cases given an interface file.

**Comment by wafflecoffee** [comment]
Already exists
https://docs.modrinth.com/api-spec

**Comment by pjalsGit** [comment]
It seems like that isn't a valid OpenAPI specification, as [this random validator I found](https://apitools.dev/swagger-parser/online/) and [Hoppscotch](https://github.com/hoppscotch/hoppscotch) fail to validate/load it.

**Comment by wafflecoffee** [comment]
I can't figure out how to satisfy these validators. There are several places where it's saying that the `required` boolean for path parameters is required. So I add `required: false`, because some path params aren't required, but guess what the validator says? It says that `false` is not a valid value. I change it to `true` and it doesn't complain. What do you want from me, validators?!?!?! Are you trying to make everything required??

If you can figure out a way to appease the validators, please open a pull request, but I cannot figure out how to make this be "valid" while still being accurate...

**Comment by wafflecoffee** [comment]
@pjalsGit The spec is now valid after #27 and #28, thank you @jakobkmar!
